# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade3e25872c8b564c3ee85b27aec6c1940871b30fa945adb1c1b31b0dfa02589fb1d91b28a7c1e245ddb18ad561947dba7ddb398dfe71a5d26169b57702fdb6b

test:
  secret_key_base: de13cd1b54959df0fbd10f69bdf2fe492860fe251bedf7f78a5c91d222abd2523a142c963a010f7bff060b789dc8a53cbe3e1d7ff2d6e43d8eaf805991f815a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
